services: # Определение сервисов (контейнеров), которые будут запускаться
  db: # Сервис базы данных PostgreSQL
    image: postgres:15 # Используем официальный образ Postgres версии 15
    container_name: instagram_db_container # Имя контейнера в Docker для удобства управления
    restart: unless-stopped # Автоматически перезапускать контейнер, если он упадёт, кроме случаев ручной остановки
    ports:
      - "${POSTGRES_PORT}:5432"
    environment: # Переменные окружения, которые передаются внутрь контейнера, чтобы настроить базу
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes: # Монтируем том для сохранения данных PostgreSQL вне контейнера (чтобы данные не потерялись при пересоздании)
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: instagram_backend_container
    restart: unless-stopped
    ports:
      - "${PORT}:3000" # Порт NestJS приложения наружу (3000)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST} # Внутреннее имя сервиса базы из этого файла - 'db'
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_URI: ${POSTGRES_URI}
    depends_on:
      - db
    command: ["bun", "run", "dev"] # Или "npm run start:dev" если используешь npm
    volumes:
      - ./:/app
      - ./gcs-credentials.json:/app/gcs-credentials.json:ro

volumes:
  pgdata: # Объявляем Docker том с именем pgdata, который будет использоваться для хранения данных базы
